# Generated by Django 3.2.9 on 2021-12-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_shoppinglist_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plan', unique=True),
        ),
    ]
