# Generated by Django 3.2.9 on 2021-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211205_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsquantities',
            name='product_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ilość produktu'),
        ),
        migrations.AlterField(
            model_name='shoppinglistproducts',
            name='product_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
