# Generated by Django 3.2.9 on 2021-12-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20211205_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_portions',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Porcje'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.DecimalField(decimal_places=1, default=4, max_digits=3, verbose_name='Porcje'),
        ),
    ]
