# Generated by Django 3.2.9 on 2021-12-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('calories', models.IntegerField(verbose_name='Zapotrzebowanie na kalorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Nazwa planu')),
                ('plan_length', models.IntegerField(verbose_name='Długość planu')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('persons', models.ManyToManyField(to='main_app.Persons', verbose_name='Osoby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_created=True, auto_now=True)),
                ('product_name', models.CharField(max_length=100, verbose_name='Nazwa produktu')),
                ('proteins', models.FloatField(null=True, verbose_name='Białka')),
                ('carbohydrates', models.FloatField(null=True, verbose_name='Węglowodany')),
                ('fats', models.FloatField(null=True, verbose_name='Tłuszcze')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsQuantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.FloatField(default=0, verbose_name='Ilość produktu')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.shoppinglist')),
            ],
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='products',
            field=models.ManyToManyField(through='main_app.ShoppingListProducts', to='main_app.Product'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_created=True, auto_now=True)),
                ('recipe_name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa przepisu')),
                ('description', models.TextField(verbose_name='Opis przygotowania')),
                ('preparation_time', models.IntegerField(verbose_name='Czas przygotowania')),
                ('portions', models.IntegerField(default=4, verbose_name='Porcje')),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('products', models.ManyToManyField(through='main_app.ProductsQuantities', to='main_app.Product', verbose_name='Produkty')),
            ],
        ),
        migrations.AddField(
            model_name='productsquantities',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productcategory', verbose_name='Kategoria'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_day', models.IntegerField(verbose_name='Dzień planu')),
                ('meal', models.IntegerField(choices=[(1, 'śniadanie'), (2, 'drugie śniadanie'), (3, 'obiad'), (4, 'podwieczorek'), (5, 'kolacja')], null=True, verbose_name='Posiłek')),
                ('meal_portions', models.IntegerField(verbose_name='Porcje')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('plan_name', models.ManyToManyField(to='main_app.Plan', verbose_name='Nazwa planu')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe', verbose_name='Przepis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
