# Generated by Django 3.2.9 on 2021-11-22 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(null=True, verbose_name='Węglowodany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productcategory', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.FloatField(null=True, verbose_name='Tłuszcze'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.FloatField(null=True, verbose_name='Białka'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='productsquantities',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
    ]
