# Generated by Django 3.2.9 on 2021-12-02 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.plan'),
        ),
    ]
