# Generated by Django 3.2.9 on 2021-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_meal_meal_portions'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
