# Generated by Django 3.2.9 on 2021-12-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_shoppinglist_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Węglowodany'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Tłuszcze'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Białka'),
        ),
    ]
