# Generated by Django 3.2.9 on 2021-11-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_plan_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.IntegerField(choices=[(1, 'śniadanie'), (2, 'drugie śniadanie'), (3, 'obiad'), (4, 'podwieczorek'), (5, 'kolacja')], null=True, verbose_name='Posiłek'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_portions',
            field=models.IntegerField(verbose_name='Porcje'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan_day',
            field=models.IntegerField(verbose_name='Dzień planu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='plan_name',
            field=models.ManyToManyField(to='main_app.Plan', verbose_name='Nazwa planu'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe', verbose_name='Przepis'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='calories',
            field=models.IntegerField(verbose_name='Zapotrzebowanie na kalorie'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='persons',
            field=models.ManyToManyField(to='main_app.Persons', verbose_name='Osoby'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_length',
            field=models.IntegerField(verbose_name='Długość planu'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.CharField(max_length=100, verbose_name='Nazwa planu'),
        ),
        migrations.AlterField(
            model_name='productsquantities',
            name='product_quantity',
            field=models.FloatField(default=0, verbose_name='Ilość produktu'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Opis przygotowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=4, verbose_name='Porcje'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(verbose_name='Czas przygotowania'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(through='main_app.ProductsQuantities', to='main_app.Product', verbose_name='Produkty'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa przepisu'),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.FloatField(default=0)),
                ('product', models.ManyToManyField(to='main_app.Product')),
            ],
        ),
    ]
