# Generated by Django 3.2.9 on 2021-11-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_shoppinglist_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='product',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='product',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='main_app.product'),
            preserve_default=False,
        ),
    ]
