# Generated by Django 3.2.9 on 2021-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20211205_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsquantities',
            name='product_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Ilość produktu'),
        ),
        migrations.AlterField(
            model_name='shoppinglistproducts',
            name='product_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
