# Generated by Django 3.2.9 on 2021-12-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20211205_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistproducts',
            name='product_quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8),
        ),
    ]
